server:
  port: 9080


spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/baby
    password: root
    username: root


  jpa:
    generate_ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
     ddl-auto: update

#Eureka
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8075/eureka/

application:
  version: task-service-v1