server:
  port: 9090


spring:
  application:
    name: User_services
  datasource:
    url: jdbc:mysql://localhost:3306/m1
    password: root
    username: root


  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

#task-service:
  #ribbon:
    #listOfServers: http://localhost:9080/

# to get same respone through eureka server i can hide ribbon to check....why u configuring this agian and agian in yml file
# u should get same respone throuht server

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8075/eureka/