server:
  port: 9090


spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/m1
    password: root
    username: root


  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

#task-service:
  #ribbon:
    #listOfServers: http://localhost:9080/

# to get same respone through eureka server i can hide ribbon to check..333no need to ribbon bcz we are in eurkha server..why u configuring this agian and agian in yml file
# u should get same respone throuht erurkha server

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8075/eureka/

application:
  version: user-service-v3